name: "3.1.$(rev:r)"

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - /tasks/EnvironmentConfiguration
      - azure-pipelines.template.yml
      - Build-Task.ps1

pr: none

workspace:
  clean: all

pool:
  name: "DAS - Continuous Deployment"

steps:
- template: /azure-pipelines.template.yml
  parameters:
    name: 'EnvironmentConfiguration'
