name: "3.1.$(rev:r)"

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - tasks/EnvironmentConfiguration
      - scripts/Build-Task.ps1

pr: none

workspace:
  clean: all

pool:
  name: 'DAS - Continuous Integration'
  demands: Agent.OS -equals Windows_NT

variables:
  ReleaseOutputDirectory: $(System.DefaultWorkingDirectory)/Release/EnvironmentConfiguration

steps:
# build and test extension
- task: PowerShell@2
  displayName: Build Task
  inputs:
    filePath: $(System.DefaultWorkingDirectory)/scripts/Build-Task.ps1
    arguments:  -Build -TaskRoot $(System.DefaultWorkingDirectory)/tasks/EnvironmentConfiguration -ReleaseOutputDirectory $(ReleaseOutputDirectory)  -Verbose
    failOnStderr: false
    pwsh: false
    workingDirectory: $(System.DefaultWorkingDirectory)
- task: PowerShell@2
  displayName: Test
  inputs:
    filePath: $(ReleaseOutputDirectory)/tests/Start-UnitTest.ps1
    failOnStderr: true
    pwsh: true
    workingDirectory: $(System.DefaultWorkingDirectory)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: "NUnit"
    testResultsFiles: $(ReleaseOutputDirectory)/tests/Test-Pester.XML
  displayName: "Publish results"
  condition: succeededOrFailed()
# tfx-cli throws circular depedency warning which is not tolerated in newer versions of node - https://github.com/microsoft/tfs-cli/issues/360
- task: NodeTool@0
  inputs:
    versionSpec: '12.x' 
- task: TfxInstaller@3
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): latest'
- task: PackageVSTSExtension@1
  inputs:
    rootFolder: $(ReleaseOutputDirectory)
    outputPath: $(ReleaseOutputDirectory)
    updateTasksVersion: false
  displayName: "Package vsix"
# publish extension
- template: ../../pipeline-templates/step/extension-publish.yml
  parameters:
    BuildDirectory: $(ReleaseOutputDirectory)
    ExtensionName: EnvironmentConfiguration
